org: upstandfm
app: api
service: lambda-authorizers

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256
  environment:
    AUTH0_JWKS_URI: 'https://upstandfm.eu.auth0.com/.well-known/jwks.json'
    AUTH0_TOKEN_ISSUER: 'https://upstandfm.eu.auth0.com/'
    AUTH0_AUDIENCE: 'https://api.upstand.fm'
    WORKSPACE_ID_OIDC_CLAIM: 'https://api.upstand.fm/workspace-id'

package:
  exclude:
    - ./*
    - ./**/*.test.js
  include:
    - node_modules
    - src

functions:
  auth0VerifyBearer:
    handler: src/auth0.verifyBearer
    description: Verifies the bearer token with the help of Auth0
